apiVersion: v1
kind: Service
metadata:
  name: cindex-web
  labels:
    app: cindex-web
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      name: http
      targetPort: 8080
      protocol: TCP
    - port: 9443
      name: https
      targetPort: 9443
      protocol: TCP
  selector:
    app: cindex-web

