[server]
host = "127.0.0.1"
port = "1323"

[database]
host = "127.0.0.1"
port = "3306"
username = "admin"
password = "password"
name = "cindex_users_db"

[messageQueue]
address = "kafka"
brokers = "127.0.0.1"
port = "9092"
topic = "afconect"
verbose = true
consumerGroup = "afconect-group"
clientId = "afconect-client"
